print("Hisssssss...")
print("............")
print("The itsy bitsy spider\nclimbed up the waterspout.")
print()
print("Down came the rain\nand washed the spider out.")
print("............")
print("My name is", "Python.", end=" ")
print("Monty Python.")
print("............")
print("My", "name", "is", sep="_", end="\n")
print("Monty", "Python.", sep="*", end="*\n")
