name: dart_fibonacci
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  system_resources: ^1.6.0
  vm_service: ^11.8.0
  resource_monitor: ^0.0.2
  system_info2: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
